### ISSUE TITLE
Relative filenames don't work

### ISSUE THREAD

**Issue by asdfklgash** [fulopattila122/smarty3-include-if-exists#1]
If you want to include a file with relative path it never works because `$_smarty_tpl->templateExists()` doesn't recognize the parent template and expand the path. So the result is always `false` for relative `file`s and the given `file` is not included.

**Comment by fulopattila122** [comment]
OK, so in case you pass a relative path and there is a parent template it should look up the template relative to the parent's path right?

**Comment by asdfklgash** [comment]
The problem is `templateExists()` because it is not able to check a file with relative path. When you use `getSubTemplate()` it works but not the check in the `if` before.

**Comment by fulopattila122** [comment]
Thanks for the report, I look into it.

**Comment by asdfklgash** [comment]
I solved the problem in a new compiler-function with other funcionality by prefixing the file with `dirname( $smarty->_current_file )` but didn't try this yet with your plugin.

**Comment by uwetews** [comment]
I like this plugin.
I provided a pull request with a complete rewrite of the plugin which should solve all problems.
- make it compatible with all Smarty 3.1 versions
- support all {include} attributes and option flags
- make it independent from {include} compiler internals and changes
- support relative template filepath

**Comment by fulopattila122** [comment]
Wow! Thank you very much Uwe, that's a real honour :)
I've merged your pull request, and tagged as 1.1.0.
